title: AAU NLP — Natural Language Processing at Aalborg University
baseURL: https://aaunlp.github.io/
languageCode: en-GB
defaultContentLanguage: en
enableRobotsTXT: true

disableKinds:
  - taxonomy
  - term
  - rss

params:
  description: The Natural Language Processing research group at Aalborg University Copenhagen develops linguistically grounded language technology for trustworthy and inclusive AI.
