main:
  - name: Research
    url: research/
    weight: 10
  - name: People
    url: people/
    weight: 20
  - name: Projects
    url: projects/
    weight: 30
  - name: Publications
    url: publications/
    weight: 40
  - name: Culture
    url: culture/
    weight: 50
  - name: News
    url: news/
    weight: 60
  - name: Collaborate
    url: contact/
    weight: 70
